import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/navbar";
import Separator from "@/components/separator";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav style={inter.style}>
        <NavBar />
      </nav>
      <main style={inter.style}>
        <section className={styles.containerHomePage}>
          <div className={styles.titleHomePage}>
            <h1>Charles de Feligonde</h1>
          </div>
          <div className={styles.descritpionHomePage}>
            <p>Etudiant en 3ème année à l’EPSI Paris <br />
              Passionné du <span>développement web</span>, j’aime <br />
              <span>créer</span> et participer à des projets.</p>
          </div>
          <div className={styles.buttonContainer}>
            <div className={styles.buttonFade}>
              <div className={styles.buttonCV}>
                <p>Mon CV</p>
              </div>
            </div>
            <div className={styles.buttonProjets}>
              <p>Projets</p>
            </div>
          </div>
        </section>
        <section className={styles.containerApropos}>
        <Separator />
          <div className={styles.containerTextApropos}>
            <div className={styles.bio}>
              <p>
                Je m'appelle Charles de feligonde, j'ai 20 ans, je suis étudiant à l'EPSI - Paris La Défense. 
                Je suis en 3ème année du programme Socle Numérique que propose l'EPSI avec obtention du BTS SIO 
                (Services Informatiques aux Organisations) avec la spécialité SLAM (Solutions Logicielles et Applications Métier). 
                Plus jeune, jamais je n'aurai pensé entrer dans ce domaine et c'est en dernière année de lycée général, 
                par manque d'idée pour mon avenir, que l'idée de me tourner vers l'informatique m'est venue. Aujourd'hui, 
                c'est grâce à ma curiosité et ma créativité que mes choix m'ont amenés vers le développement.
              </p>
            </div>
            <div className={styles.returnCards}>
              <div>

              </div>
              <div>

              </div>
              <div>

              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
